#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# for jq
PATH=/usr/local/bin:$PATH

payload="$(cat <&0)"

version=$(jq -r '.version // ""' <<< $payload)

if [ -n "${version}" ]; then
  jq -r '{ version: .version }' <<< $payload >&3
else
  echo "{}" >&3
fi
