#@ load("@ytt:data", "data")

#@ def resource_image():
#@   return data.values.docker_registry + "/honeymarker-resource"
#@ end

jobs:
- name: build-image-image
  serial: true
  plan:
  - {get: repo, trigger: true}
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: repo
      outputs:
      - name: image
      params:
        CONTEXT: repo
      run:
        path: build
  - put: edge-image
    params:
      image: image/image.tar

resources:
- name: repo
  type: git
  source:
    ignore_paths: ["ci/*[^md]"]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch

- name: edge-image
  type: registry-image
  source:
    tag: edge
    username: #@ data.values.docker_registry_user
    password: #@ data.values.docker_registry_password
    repository: #@ resource_image()
